directories:
  output: releases
  buildResources: .
appId: com.atnos.pia
mac:
  publish:
    - github
  category: public.app.category.productivity
win:
  target: nsis
  publish:
    - github
  verifyUpdateCodeSignature: false
  publisherName: ATNOS
linux:
  publish:
    - github
  category: Network
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
electronVersion: 2.0.1
